log_dest stdout
log_type error
log_type warning
log_type notice
connection_messages true

# Debug profile (temporary troubleshooting):
# 1) Comment the 4 production log lines above.
# 2) Uncomment the lines below.
log_dest stdout
log_type all
connection_messages true

# --- CONNECTION 1: Your Broker (Broker A) ---
connection bridge-to-account-A
address a3tjieanngjl2e.iot.us-east-1.amazonaws.com:8883
remote_clientid 99999008
bridge_cafile /etc/mosquitto/certs/A/AmazonRootRSA_CAs.pem
bridge_certfile /etc/mosquitto/certs/A/certificate.pem.crt
bridge_keyfile /etc/mosquitto/certs/A/private.pem.key
bridge_tls_version tlsv1.2
bridge_protocol_version mqttv311
bridge_insecure false
cleansession true
start_type automatic
try_private false
notifications false
# Map specific topic (test: LTENode_nRF9160/my/subscribe/topic)
topic LTENode_nRF9160/my/subscribe/topic both 1 bridge/A/ ""

# --- CONNECTION 2: Their Broker (Broker B) ---
connection bridge-to-account-B
address mqtt.ulogger.ai:8883
remote_clientid cust-818320739
bridge_cafile /etc/mosquitto/certs/B/AmazonRootRSA_CAs.pem
bridge_certfile /etc/mosquitto/certs/B/certificate.pem.crt
bridge_keyfile /etc/mosquitto/certs/B/private.pem.key
bridge_tls_version tlsv1.2
bridge_protocol_version mqttv311
bridge_insecure false
cleansession true
start_type automatic
try_private false
notifications false
# Map specific topic (test: boot/v0/818320739/494121/1)
topic boot/v0/818320739/494121/1 both 1 bridge/B/ ""
