log_dest stdout
log_type error
log_type warning
log_type notice
connection_messages true

# Debug profile (temporary troubleshooting):
# 1) Comment the 4 production log lines above.
# 2) Uncomment the lines below.
log_dest stdout
log_type all
connection_messages true

# --- CONNECTION 1: Your Broker (Broker Waites IoT Core) ---
connection bridge-to-account-waites
address a3tjieanngjl2e.iot.us-east-1.amazonaws.com:8883
remote_clientid 99999008
bridge_cafile /etc/mosquitto/certs/waites/AmazonRootRSA_CAs.pem
bridge_certfile /etc/mosquitto/certs/waites/certificate.pem.crt
bridge_keyfile /etc/mosquitto/certs/waites/private.pem.key
bridge_tls_version tlsv1.2
bridge_protocol_version mqttv311
bridge_insecure false
cleansession true
start_type automatic
try_private false
notifications false
# Bridge A topic namespace:
#   Remote Broker Waites: ulogger/<x>
#   Local broker:    <x>
# This strips "ulogger/" from inbound Waites traffic and adds it for outbound to Waites.
topic # in 1 "" ulogger/

# This is the boot message response topic filter for inbound Waites traffic.
topic boot/v0/551826890/+/+ out 1 "" ulogger/

# --- CONNECTION 2: Their Broker (Broker uLogger) ---
connection bridge-to-account-ulogger
address mqtt.ulogger.ai:8883
remote_clientid cust-551826890
bridge_cafile /etc/mosquitto/certs/ulogger/AmazonRootRSA_CAs.pem
bridge_certfile /etc/mosquitto/certs/ulogger/certificate.pem.crt
bridge_keyfile /etc/mosquitto/certs/ulogger/private.pem.key
bridge_tls_version tlsv1.2
bridge_protocol_version mqttv311
bridge_insecure false
cleansession true
start_type automatic
try_private false
notifications false
# Bridge uLogger topic namespace:
#   Remote Broker uLogger: <x>
#   Local broker:    <x>
# This is the boot message response topic filter for inbound uLogger traffic.
topic boot/v0/551826890/+/+ in 1 "" ""

# These are the topic filters for outbound uLogger traffic. They mirror the filters for inbound Waites traffic, but without the "ulogger/" prefix.
topic boot/v0/551826890/+ out 1 "" ""
topic binlog/v0/551826890/+ out 1 "" ""
topic core-dump/v0/551826890 out 1 "" ""
